server:
  port: 8700

eureka:
  instance:
    hostname: peer0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:8702/eureka/,http://peer1:8701/eureka/
spring:
  application:
    name: eureka-service
