spring:
  application:
    name: compute-service
server:
  port: 8900

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/,http://locakhost:8701/eureka/,http://locakhost:8702/eureka/
